### ISSUE TITLE
issues with custom data

### ISSUE THREAD

**Issue by Esraanageh22** [alankbi/detecto#108]
iam trying to training with custom data but the error in the image stopped me, so i have tested my data as shown in the images and data were fine can you help me please?

**Environment:**
colab 
![ask51](https://user-images.githubusercontent.com/73080410/159067004-f5ffb43f-e681-444a-858e-15930e68e679.PNG)

there are the data:

![ask1](https://user-images.githubusercontent.com/73080410/159035700-a5e0c014-465f-434a-9664-3a0135fa2b00.PNG)

When checking data:

![ask2](https://user-images.githubusercontent.com/73080410/159035707-6acdca04-3734-4fce-8984-a8a3fea5b217.PNG)
![ask3](https://user-images.githubusercontent.com/73080410/159035709-7902b7ca-b587-454c-a0fd-5d52e80fd5ac.PNG)

**Comment by alankbi** [comment]
Discussion continued in #63
