### ISSUE TITLE
detect_video odd behavior

### ISSUE THREAD

**Issue by carlok** [alankbi/detecto#110]
Hi,
On a sample video, I tried `detect_video` using its default settings

```
model = core.Model()
```

and the result is very good, IMHO.

Check it here: [detect_video default](https://www.youtube.com/watch?v=kQEsosNxcf4)

Then I changed the model to

```
model = core.Model(['car'])
```

and a lot of false positives oddly appeared.

Check it here: [detect_video with a class](https://www.youtube.com/watch?v=hgz7jdhWI2U)

I didn't expected this.

As a reference (or if you want to reproduce the behavior) this is the [original video](https://www.youtube.com/watch?v=rSEdYDwafkY).

Thank you anyway.

**Comment by alankbi** [comment]
Did you retrain the dataset after passing in the custom set of classes? The default model is pretrained, but if you want the model to be able to predict custom classes (in this case, only cars), you would have to retrain on your own dataset so it can properly update its weights (it isn't able to know that the 'car' class you specified is the same as the 'car' in the default list of classes). 

Another solution would be to use the default model and write your own `detect_video` function that specifically filters and displays only the car labels.

**Comment by carlok** [comment]
I know it is pretrained and, knowing which labels is trained on (car is one of them) I supposed passing labels to `detect_video` was a way to filter the original label inside your code but that's not the case. Thank you for your answer. I checked the code of `detect_video` and a custom version of it is not too complex.

**Comment by alankbi** [comment]
Awesome! Will close this issue in that case
