### ISSUE TITLE
Time for running the model fit

### ISSUE THREAD

**Issue by filipeandresubtas** [alankbi/detecto#20]
Hi, Alan
i´m trying to execute your dataset ( with chihuahuas and golden retriever ). however, when i execute the model fit code, this calculations take more than 3 hours. I would like to ask you if this time is normal or not.

**Comment by alankbi** [comment]
If you're running your code on a personal computer and it doesn't have access to a CUDA-enabled GPU, it will likely take a very long time (several hours, maybe even more). However, with a GPU, it shouldn't take more than 10-20 minutes. To check if you have a GPU enabled, you can run the following Python code: 

```python
import torch

print(torch.cuda.is_available())
```

If it's not available, then you can also try using a service like Google Colab, which comes with a free GPU that you can use; see [here](https://colab.research.google.com/notebooks/intro.ipynb) for an intro to Colab and the "Getting access to a GPU" section [here](https://towardsdatascience.com/build-a-custom-trained-object-detection-model-with-5-lines-of-code-713ba7f6c0fb) for how to set it up with Detecto.

**Comment by alankbi** [comment]
Marking this issue as resolved.
