### ISSUE TITLE
Hard negative mining

### ISSUE THREAD

**Issue by LexRillo** [alankbi/detecto#25]
Hello,
Is there a way that detecto deals with having no labels present in one of the images? For example, if we are tracking an object and that object is occluded, how does Dataset with that image missing a track?
Thank you

**Comment by alankbi** [comment]
If there are no labels in an image, the model and dataset will simply skip that image when training or iterating over the images. In other words, it shouldn't affect the accuracy of the model.

**Comment by LexRillo** [comment]
Thank you for you quick answer. Also Detecto is amazing.
