### ISSUE TITLE
Can we choose different models apart from Faster R-CNN ResNet-50 FPN?

### ISSUE THREAD

**Issue by sreeni5493** [alankbi/detecto#30]
Can we choose mobilenet, SSD, YOLO?

**Comment by alankbi** [comment]
Currently only Faster R-CNN ResNet-50 FPN is supported, but check back in a few months for potential updates!

**Comment by chupachupbum** [comment]
Any update on this? I want to change to Mobilenet, is there any ways to achieve this?

**Comment by alankbi** [comment]
Unfortunately not with Detecto. However, if you're interested in say YOLO, I'd recommend checking out this project: https://github.com/ultralytics/yolov5

**Comment by chupachupbum** [comment]
> Unfortunately not with Detecto. However, if you're interested in say YOLO, I'd recommend checking out this project: https://github.com/ultralytics/yolov5

Thanks for your suggestion, YOLO works well for me.
