### ISSUE TITLE
Is there a way to print training accuracy metrics?

### ISSUE THREAD

**Issue by sreeni5493** [alankbi/detecto#31]
The current verbose does provide information apart from just epoch information. Is there a way to plot training accuracy.

Also, is there a way to get these values of training accuracy. So that we can plot our own graphs?

**Comment by alankbi** [comment]
Not training accuracy, but if you pass in a validation dataset and have verbose set to true, then it should print out the validation loss at each step and also return the list of losses when training is finished; hope that helps.
