### ISSUE TITLE
Displaying Scores on still images

### ISSUE THREAD

**Issue by halbinali** [alankbi/detecto#32]
How can I display confidence level score on still images?

**Comment by alankbi** [comment]
It's not supported in the package, but if you take a look at the [source code](https://github.com/alankbi/detecto/blob/master/detecto/visualize.py#L254) for the `show_labeled_image` function, that should give you some examples for how you can define a custom function that plots the scores. For example, you could modify [line 304](https://github.com/alankbi/detecto/blob/master/detecto/visualize.py#L304) from this: 

```python
ax.text(box[0] + 5, box[1] - 5, '{}'.format(labels[i]), color='red')
```

To this (given that you have an iterable called `scores`): 

```python
ax.text(box[0] + 5, box[1] - 5, '{}: {}'.format(labels[i], round(scores[i].item(), 2)), color='red')
```
