### ISSUE TITLE
Not detecting the custom object

### ISSUE THREAD

**Issue by prasad01dalavi** [alankbi/detecto#36]
have trained the model on about 126 images, 30% images contain two objects in a image

```
from detecto import core, utils, visualize


dataset = core.Dataset('../custom_dataset/')
model = core.Model(['stamp'])

model.fit(dataset)
model.save('model_weights_3.pth')
print(f'[INFO] Model Saved successfully!')
image = utils.read_image('../custom_dataset/page-15.jpg')
predictions = model.predict(image)
print(predictions)
```

Output:
```
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:2854: UserWarning: The default behavior for interpolate/upsample with float scale_factor will change in 1.6.0 to align with other frameworks/libraries, and use scale_factor directly, instead of relying on the computed output size. If you wish to keep the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  warnings.warn("The default behavior for interpolate/upsample with float scale_factor will change "
[INFO] Model Saved successfully!
([], tensor([], size=(0, 4)), tensor([]))
```

**Comment by alankbi** [comment]
It looks like the model was unable to detect any stamps in that image. It could be that the image you used was very difficult for it to predict on, or possibly your model has poor accuracy even after training. You can check how well your model is doing by passing it a validation dataset and setting `verbose=True` when calling the `fit` method.

**Comment by prasad01dalavi** [comment]
Hi, thanks for the reply
the image for prediction is out of training sample only

**Comment by alankbi** [comment]
For the first error: see if the suggestions in #33 help. As for the nan losses, could you share what the output of `len(dataset)` and `dataset[0]` are?

**Comment by prasad01dalavi** [comment]
Output for dataset[0]
```

[INFO] Dataset Sample: (tensor([[[2.2489, 2.2489, 2.2489,  ..., 2.2489, 2.2489, 2.2489],
         [2.2489, 2.2489, 2.2489,  ..., 2.2489, 2.2489, 2.2489],
         [2.2489, 2.2489, 2.2489,  ..., 2.2489, 2.2489, 2.2489],
         ...,
         [2.2489, 2.2489, 2.2489,  ..., 2.2489, 2.2489, 2.2489],
         [2.2489, 2.2489, 2.2489,  ..., 2.2489, 2.2489, 2.2489],
         [2.2489, 2.2489, 2.2489,  ..., 2.2489, 2.2489, 2.2489]],

        [[2.4286, 2.4286, 2.4286,  ..., 2.4286, 2.4286, 2.4286],
         [2.4286, 2.4286, 2.4286,  ..., 2.4286, 2.4286, 2.4286],
         [2.4286, 2.4286, 2.4286,  ..., 2.4286, 2.4286, 2.4286],
         ...,
         [2.4286, 2.4286, 2.4286,  ..., 2.4286, 2.4286, 2.4286],
         [2.4286, 2.4286, 2.4286,  ..., 2.4286, 2.4286, 2.4286],
         [2.4286, 2.4286, 2.4286,  ..., 2.4286, 2.4286, 2.4286]],

        [[2.6400, 2.6400, 2.6400,  ..., 2.6400, 2.6400, 2.6400],
         [2.6400, 2.6400, 2.6400,  ..., 2.6400, 2.6400, 2.6400],
         [2.6400, 2.6400, 2.6400,  ..., 2.6400, 2.6400, 2.6400],
         ...,
         [2.6400, 2.6400, 2.6400,  ..., 2.6400, 2.6400, 2.6400],
         [2.6400, 2.6400, 2.6400,  ..., 2.6400, 2.6400, 2.6400],
         [2.6400, 2.6400, 2.6400,  ..., 2.6400, 2.6400, 2.6400]]]), {'boxes': tensor([[ 380, 1371,  736, 1595]]), 'labels': 'stamp'})
```

**Comment by alankbi** [comment]
I'm trying to reproduce this error, as it seems a lot of people are having it. Could you provide me with as many details as you can regarding your environment? Python version, PyTorch/torchvision versions, code environment, etc. 

In addition, if you're able to, it'd be helpful if you can send me your trained model file and some images through [email](mailto:alan.bi326@gmail.com). This will help me see whether the error is specific to certain use cases, as right now when I run the code on my end, no error occurs.

**Comment by jagilley** [comment]
Since I'm having the same issue, I'll share the dataset + trained model that's giving this error with you via Google Drive as well!

**Comment by prasad01dalavi** [comment]
I have got one conclusion that 
When we install depedencies with 
`pip install detecto`

we have```
 torchvision==0.6.0+cu101
detecto==1.1.3
tensorflow==2.2.0
```

i didnot get any error, also prediction did not happen and got a blank tensor

when we install dependencies with
`pip install -r requirements.txt`

We get this error
`RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1] because the unspecified dimension size -1 can be any value and is ambiguous
`
and we have
torchvision              0.6.0+cu101    
tensorflow               2.2.0          


In both the cases Python Version: 3.6.9

**Comment by alankbi** [comment]
@prasad01dalavi so you're saying the error goes away when you run it with `pip install detecto`? If so, can you try the suggestions in my first comment again regarding setting `verbose=True` to see what the model loss is while training? Blank tensors are a sign that your model might not be trained well enough. 

@jagilley spent some time going through your Drive folder to see if I could get it to work (I created a Colab file which you can browse through, but it's very messy). It seems like there's some issue with your dataset for some reason, which is causing `nan` losses to come up every time during training: 

```
{'loss_classifier': tensor(nan, device='cuda:0', grad_fn=<NllLossBackward>), 'loss_box_reg': tensor(nan, device='cuda:0', grad_fn=<DivBackward0>), 'loss_objectness': tensor(nan, device='cuda:0', grad_fn=<BinaryCrossEntropyWithLogitsBackward>), 'loss_rpn_box_reg': tensor(inf, device='cuda:0', grad_fn=<DivBackward0>)}
```

I'm not sure why this is the case, but I can try looking deeper into it over the next few days. In the meantime though, hopefully this helps a bit in clearing up what exactly is happening.

**Comment by prasad01dalavi** [comment]
you were absolutely right!  there is a problem in dataset. one of the xml file filename was not matching with image name. i removed them, rechecked the dataset and file names. 

continued with pip install detecto

and boom, it predicted my object with 0.96 confidence..thanks alot
