### ISSUE TITLE
Continue training a trained model

### ISSUE THREAD

**Issue by JacobusS** [alankbi/detecto#41]
Is it possible to continue training a model that I trained?

I have trained a model successfully, but have received new data. Is it possible to continue training the already trained model. I read through the docs but might have missed it if it's already a feature.
I have tried to rename the fasterrcnn_resnet50_fpn_coco-258fb6c6.pth file and renaming my trained model to fasterrcnn_resnet50_fpn_coco-258fb6c6.pth. But that only resulted in an error.

Thanks.

**Comment by alankbi** [comment]
Yes, if you load the model into a `core.Model` object, you can continue to call the `fit` method as many times as you want, and once you're done, save it back to a .pth file.

**Comment by JacobusS** [comment]
> Yes, if you load the model into a `core.Model` object, you can continue to call the `fit` method as many times as you want, and once you're done, save it back to a .pth file.

Thanks!!
