### ISSUE TITLE
Runtime error during model.fit

### ISSUE THREAD

**Issue by anirudh-g** [alankbi/detecto#42]
When running model.fit() I get the following error message on google colab:
RuntimeError                              Traceback (most recent call last)
<ipython-input-26-14c0326ceff3> in <module>()
----> 1 model = core.Model(['title', 'legend', 'axis label'])
      2 val_dataset = core.Dataset('Validation/')
      3 model.fit(dataset, val_dataset, verbose=True)

6 frames
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in convert(t)
    421 
    422         def convert(t):
--> 423             return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
    424 
    425         return self._apply(convert)

RuntimeError: CUDA error: device-side assert triggered

This is on gpu acceleration, with pythorch 1.4 and torchvision 0.5.0

**Comment by anirudh-g** [comment]
While the error message stays the same, the stacktrace alternates between the above and below mentioned one for every run

Epoch 1 of 10
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-11-14c0326ceff3> in <module>()
      1 model = core.Model(['title', 'legend', 'axis label'])
      2 val_dataset = core.Dataset('Validation/')
----> 3 model.fit(dataset, val_dataset, verbose=True)

6 frames
/usr/local/lib/python3.6/dist-packages/torchvision/ops/boxes.py in remove_small_boxes(boxes, min_size)
     93     ws, hs = boxes[:, 2] - boxes[:, 0], boxes[:, 3] - boxes[:, 1]
     94     keep = (ws >= min_size) & (hs >= min_size)
---> 95     keep = keep.nonzero().squeeze(1)
     96     return keep
     97 

RuntimeError: copy_if failed to synchronize: cudaErrorAssert: device-side assert triggered

**Comment by alankbi** [comment]
Could you try switching to CPU and running it again? That might help with getting a more meaningful error message.

**Comment by anirudh-g** [comment]
Yes. I tried that I found the error. Thank you
Is there a way that I can get accuracy from model.fit instead of losses?

**Comment by alankbi** [comment]
Great, glad you found the error!

The `fit` method only returns the losses, so you'd have to write your own function if you want to gather accuracy. As for confidence level, when you use any of the functions in the `visualize` module, you can set a `score_filter` parameter to remove any predictions below a certain score.

**Comment by anirudh-g** [comment]
As per the documentation in https://detecto.readthedocs.io/en/latest/api/visualize.html, the score_filter parameter only seems to be accepted for a video input or for multiple input images (through plot_prediction_grid). For the prediction of a single input image, it does not accept a score_filter
