### ISSUE TITLE
Multiple of the same object in a model with multiple objects

### ISSUE THREAD

**Issue by benjheath** [alankbi/detecto#43]
Hi, having a bit of an issue with a model that I've trained. I've trained a model with currently 3 objects, with plans to expand to more. The problem I am having is when I provide an image to use the model on with for example 3 instances of one of the objects, even with using the function .predict and not .predict_top, only one of the objects in picked up. However, when I use a model specifically trained on only 1 object (with the same number of training and validation images) and apply it to the same image, all 3 of the instances of the object are picked up. 

<img width="634" alt="OH objects detected when using the model with multiple labels" src="https://user-images.githubusercontent.com/28192616/88595399-c50fc300-d05a-11ea-8fa0-2e660a6e7543.png">

<img width="632" alt="OH objects detected when using the model with only 1 label - same amount of training images for both models" src="https://user-images.githubusercontent.com/28192616/88595403-c7721d00-d05a-11ea-9155-85963394776c.png">

Great if I could have some insight into this, am very new to this and your module is really easy to use and great so thanks for all your work on it.

**Comment by alankbi** [comment]
Which three object labels are you training it to detect? From an initial look, it seems you might want to use 2 labels, one for "OH" and one for "HO". As for `predict` vs. `predict_top`, I think `predict` better suits your use case, given that the image has multiple "OH" objects that you're trying to detect.

**Comment by benjheath** [comment]
Good suggestion - I will probably create a HO label and add that to the model. I am building a chemistry skeletal formula recognition program - so the 3 object labels I'm training it to detect are double bonds (I'm using the 'DB' label for this in my code), the ketone functional group (using the 'KT' label for this) and the OH alcohol functional group (using the 'OH' label). I have been using predict - but my question is why when I apply the predict to the image in my original question does it only return one possible match? It should be returning at least the other OH as a possible match, as the other model does.

**Comment by alankbi** [comment]
That's definitely odd, as if your model is trained well, then it should be able to detect most of the objects and labels in the image. Have you trained passing in a validation dataset when calling the `fit` method? This will help you gauge how well your model is training when you have 1 vs. 3 object labels.

**Comment by benjheath** [comment]
I know - it seems really odd. I have been passing a validation dataset and it has been training well, but realistically I realise I could have more images in my dataset. I'm going to add more images and train it better and see the results - again thanks for all your help and thanks for creating a great module.

**Comment by benjheath** [comment]
having a more robust model fixed this weird issue - thanks for all the help I'm closing the issue
