### ISSUE TITLE
Pin the version of packages in requirements

### ISSUE THREAD

**Issue by cpatrickalves** [alankbi/detecto#52]
Would be great if you set the versions of each package on the requirements.txt file.

Example:
```
torch==1.2.0
torchvision==0.4.0
```

As it is it will try to get the last version of the packages, but these may not work properly in the long term.

**Comment by alankbi** [comment]
Closed by the release of [v1.2.0](https://github.com/alankbi/detecto/releases/tag/v1.2.0) - note that I pinned the versions of torch and torchvision, but left the other dependencies free to change for now
