### ISSUE TITLE
Note CPU performance insufficent?

### ISSUE THREAD

**Issue by Matthias84** [alankbi/detecto#53]
**Describe the feature you'd like**
Add techniques and docs that help people without adequate Nvidia GPU to get started with detecto to fit custom models.
Currently you see only @Epoch 1...@ but don't see any progress even in hours or running all night long.

**Describe the use cases of the feature**
Detecto is considered as high level abstraction to simplify getting working models and to train models. 
Thus users are usually not familar with complex installation process of CUDA / don't own a supported NVIDIA card / ...
But if you currently start training a custom model, there is nothing more than a hint, that it will take long time on CPU only. This results in frustration, as the simplified process now gets suddenly more complex. This isn't a easy start to the world of ML for object detection.

**Additional context**
I suggest to give the users more assistance on how to start custom model training, even if they use only a CPU
- Show more logging during training 
- check if training material is performant (resolution, size , size validation set)
- estimate rough training duration based on number of images
- document experiences (me: Training on i7 6600 16GB RAM, win10 has never finished epoch 1 for >8hrs
- tipps on general speedup (shrinked size, resolution, ...)

**Comment by alankbi** [comment]
Thanks for the suggestion - I incorporated parts of this in the release of [v1.2.0](https://github.com/alankbi/detecto/releases/tag/v1.2.0). In particular, it now shows you the progress through each epoch and gives users a warning if they're using a CPU. 

Unfortunately, I don't think Detecto (or even just object detection models in general) will ever run in a reasonable amount of time on a normal CPU in the foreseeable future, so I'd definitely recommend checking out [Colab](https://colab.research.google.com/) or something similar for a free GPU if you don't have one.
