### ISSUE TITLE
invoke multi-gpu from DataLoader?

### ISSUE THREAD

**Issue by bgriffen** [alankbi/detecto#55]
I'm on a multi-gpu setup but out of the box it appears that only one is being invoked by detecto.

```
from detecto.core import Dataset, DataLoader
from detecto.core import Model
bpath = '/image_and_xml_path/'
dataset = Dataset(bpath, bpath)
loader = DataLoader(dataset, batch_size=4)
val_dataset = Dataset('validation/')
model = Model(['A','B']) 
losses = model.fit(loader,val_dataset,epochs=20,verbose=True)
plt.plot(losses)
plt.show()
```

Is there an argument for DataLoader that will ensure the underlying model calls both cuda devices? THanks.

**Comment by alankbi** [comment]
You can specify a torch device option when initializing Model, but I don't think using multiple GPUs is supported out of the box with Detecto. It may require some more advanced parallelism techniques with PyTorch [see here](https://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html)

**Comment by gunners81** [comment]
can you please give an example how to initializing Model using parallelism techniques ?
