### ISSUE TITLE
Bounding boxes with invalid coordinates 

### ISSUE THREAD

**Issue by lautarodc** [alankbi/detecto#56]
Hello everyone, 

I've found an issue trying the google colab example with a custom dataset of flowers built with labelimg during the training stage. 

> Epoch 1 of 10
> /usr/local/lib/python3.6/dist-packages/torchvision/ops/boxes.py:101: UserWarning: This overload of nonzero is deprecated:
> 	nonzero()
> Consider using one of the following signatures instead:
> 	nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
>   keep = keep.nonzero().squeeze(1)
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-12-8d86f73f8563> in <module>()
>      11 # Train the model! This step can take a while, so make sure you
>      12 # the GPU is turned on in Edit -> Notebook settings
> ---> 13 losses = model.fit(loader, val_dataset, epochs=10, verbose=True)
>      14 
>      15 # Plot the accuracy over time
> 
> 2 frames
> /usr/local/lib/python3.6/dist-packages/torchvision/models/detection/generalized_rcnn.py in forward(self, images, targets)
>      91                     raise ValueError("All bounding boxes should have positive height and width."
>      92                                      " Found invaid box {} for target at index {}."
> ---> 93                                      .format(degen_bb, target_idx))
>      94 
>      95         features = self.backbone(images.tensors)
> 
> ValueError: All bounding boxes should have positive height and width. Found invaid box [-8.646100394725868e+18, -8.635381805622493e+18, -8.646100394725868e+18, -8.635381805622493e+18] for target at index 0.

I've checked the xml files and all the coordinates lie inside the images boundaries. Here is the link to the folder with the dataset and the google colab. 

[https://drive.google.com/drive/folders/1vBLrgJbjohAMwlNR-ABs9fKOIACqHn-1?usp=sharing](url)

Thanks in advance!

**Comment by alankbi** [comment]
Do you get the same error if you change the way you create the datasets to the following?

```python
core.Dataset('train_labels/', 'images/', transform=transform_img)
```

If so, could you run something similar to the following code to see if there are any invalid boxes in your dataset:

```python
for i in range(len(dataset)):
    image, target = dataset[i]
    box = target['boxes']
    if box[0] >= box[2] or box[1] >= box[3]: # min x > max x or min y > max y
        print(i, box)

```

**Comment by lautarodc** [comment]
I was getting the same error creating the dataset with the folder instead of the csv. Luckily I was able to find the issue. Although all the xml had correct bounding boxes coordinates, one of them had a width and height of zero so in the end it was a problem with labelimg. I removed the image and is working great now. Thanks for the help!
