### ISSUE TITLE
xml_to_csv.py converts many class labels in a image item to single class

### ISSUE THREAD

**Issue by Sathyakumarnsk** [alankbi/detecto#58]
HI! The xml_to_csv.py converts my multiple class labels in every image item to single class per image item at the end of xml_to_csv.py.  Is this the right feature or a bug?
After training as well, my model only recognises single class per image item. How can I enable multi-class detection?

**Comment by alankbi** [comment]
If you have multiple labels in an image, `xml_to_csv` should be able to detect all of them, although each label in an image will correspond to a separate row in the CSV file. 

Same thing for the second part - it could be that there's a bug with the label files, or maybe your model isn't being trained properly. If the error is still happening, feel free to share the code and I can take a closer look.

**Comment by alankbi** [comment]
This has just been addressed in the release of [v1.2.0](https://github.com/alankbi/detecto/releases/tag/v1.2.0) - note that `xml_to_csv` is just a helper function and still returns multiple class labels in separate rows; however, the Dataset class now has some added logic (courtesy of @TasinIshmam) which groups the labeled objects by image when indexing.
