### ISSUE TITLE
Why need a "__background__" class?

### ISSUE THREAD

**Issue by chamecall** [alankbi/detecto#59]
Can you explain the meaning of addition "__background__" class to my classes?
Where/how it is used and what it affects?

**Comment by alankbi** [comment]
1. Background is just the base class that the PyTorch models require to help deal with not finding any objects. If the model can't detect anything in an image, I think internally it predicts the background class (as an end-user you shouldn't have to worry about using/seeing that label at all though). 

2. If you pass in a list of N images to the internal model, then it should output a list of dicts of size N. Each dict corresponds to an image and has the keys 'labels', 'boxes', and 'scores'. You can also read more about it [here](https://pytorch.org/docs/stable/torchvision/models.html#faster-r-cnn). 

Hope that helped clear up some of your questions!

**Comment by alankbi** [comment]
Closing this for now - feel free to reach out again if you have any follow up/additional questions :)
