### ISSUE TITLE
AttributeError: 'Image' object has no attribute 'to'

### ISSUE THREAD

**Issue by sosojni** [alankbi/detecto#61]
**Describe the bug**
When i try to use torchvision.transforms.ToPILImage() i get following error:
AttributeError: 'Image' object has no attribute 'to'

**Code and Data**
Code where i call is looks like this:
```
self.dataset = core.Dataset(
	'dataset/data/train/images',
	transform=torchvision.transforms.Compose([
		torchvision.transforms.ToPILImage(),
		torchvision.transforms.RandomPerspective()
	])
)
```
Some other transforms like: torchvision.transforms.ToTensor() are working without of error, and if i don't use transforms, model is working (i am trying to get better precision by using transforms)

**Environment:**
 - OS: win10
 - Python version: 3.6
 - Detecto version: 1.1.6
 - torch version: 1.6.0
 - torchvision version: 0.7.0

**Comment by alankbi** [comment]
If you use custom transforms, the last transform that you use will likely have to be `torchvision.transforms.ToTensor()`

**Comment by sosojni** [comment]
Wow, that's it! I thought transforms are working in steps and that problem lies somewhere in torchvision.transforms.ToPILImage() part of code. Turns out i'm clueless 😃 
My code now looks like this:
```
self.dataset = core.Dataset(
	'dataset/data/train/images',
	transform=torchvision.transforms.Compose([
		torchvision.transforms.ToPILImage(),
		torchvision.transforms.RandomPerspective(),
		torchvision.transforms.ToTensor()
	])
)
```
and training is under way.
Thanks!

**Comment by alankbi** [comment]
Glad I could help :)
