### ISSUE TITLE
Cannot see detection results on Colab

### ISSUE THREAD

**Issue by SpeedyCraftah** [alankbi/detecto#70]
**Describe the bug**
Unable to see the prediction result image with `show_labeled_image`.

**Code and Data**
![image](https://user-images.githubusercontent.com/45142584/100280084-84b84700-2f5f-11eb-8475-204baabb0ba1.png)
![image](https://user-images.githubusercontent.com/45142584/100280221-b6c9a900-2f5f-11eb-9947-d74bd758394e.png)

**Environment:**
 - OS: Google Colab
 - Python version: 3.6
 - Detecto version: Latest
 - torch version: Latest
 - torchvision version: Latest

**Additional context**
None.

**Comment by alankbi** [comment]
This seems to be an issue more to do with Colab. One option I think is to simply copy the Python code from the `predict.py` script into the cell block directly. Another option would be to use `%run predict.py` as shown [here](https://stackoverflow.com/questions/59977900/how-to-plot-with-pyplot-from-a-script-file-in-google-colab) and see if that works
