### ISSUE TITLE
Cropping the area of bounding box predicted by the model.

### ISSUE THREAD

**Issue by 1skol1** [alankbi/detecto#86]
Hey Everyone,

 I am having a problem cropping out the bounding box area predicted by the model(need it for OCR), as the values are in float, making them integers covers more area than needed. Can someone help me with a workaround?

Here's the code
`def cropped_area(img,boxes):
    x, y, w, h = boxes
    roi = img[y:y + h, x:x + w]
    plt.imshow(roi)`

**Comment by alankbi** [comment]
Not sure about the float vs. int thing, but another thing is did you keep in mind that the returned boxes are in xmin, ymin, xmax, ymax format? From your code it seems like you're treating the last two as widths and heights

**Comment by 1skol1** [comment]
Thanks for pointing that out.
