### ISSUE TITLE
Missing `model.pth` causing tests to fail

### ISSUE THREAD

**Issue by 1nF0rmed** [alankbi/detecto#95]
**Describe the bug**
When running the tests using the command:
`python3 -m pytest`

would result in the test case for `test_model_predict` to fail. This is because the file mentioned in path `static/model.pth` under the `tests` folder doesn't exist in the repository.

**Code and Data**
Share the code that caused the error as well as an example image/label from your dataset.

Line resulting in test failure:
https://github.com/alankbi/detecto/blob/f4e60968b052406194f47fc3d782913ce163f223/detecto/tests/test_core.py#L157

Folder missing the specified files:
https://github.com/alankbi/detecto/tree/master/detecto/tests/static

**Environment:**
 - OS:  macOS Big Sur
 - Python version: 3.7.9
 - Detecto version: master branch
 - torch version: 1.6.0
 - torchvision version: 0.7.0

**Additional context**
NA

**Comment by alankbi** [comment]
The reason why this fails is because the pth file is too large to be uploaded with the source code, so the model file needs to be downloaded separately at [this link](https://www.dropbox.com/s/kjalrfs3la97du8/model.pth?dl=1). 

Also, [this link](https://github.com/alankbi/detecto/blob/e003f1b1d642edfb20c71f7dfc1a305ead27cff5/.circleci/config.yml#L50) has an example of how one can do that via the command line.

**Comment by 1nF0rmed** [comment]
Thanks for the link!
But this information doesn't seem to be present on the [README](https://github.com/alankbi/detecto#contributing).
The linked config file for the CI pipeline doesn't seem to be on the master branch, have we removed the CircleCI pipeline that runs when merging code / making PRs?

**Comment by alankbi** [comment]
Yeah, it was removed from the master branch in a recent commit because the CircleCI always failed due to some kind of dependency issue that I wasn't able to resolve.

**Comment by 1nF0rmed** [comment]
I'd like to work on that (if it's not picked up yet). Will make a couple of PRs over the week for the same.

**Comment by alankbi** [comment]
Added a note in the README to clear this up and hopefully clarify things for the future - see further discussion in #97
